name: kthcloud-ci

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checka ut kod från repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Ställ in JDK 19
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
          cache: maven

      # 3. Bygg projektet med Maven och skapa .jar-filen
      - name: Build with Maven
        run: mvn --file ./pom.xml --batch-mode --update-snapshots package -DskipTests

      # 4. Kontrollera att .jar-filen skapades
      - name: Verify .jar file
        run: ls -la ./target

      # 5. Logga in på KTH Cloud Docker Registry
      - name: Login to KTH Cloud Registry
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 6. Bygg och pusha Docker-image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          push: true
          tags: registry.cloud.cbh.kth.se/${{ secrets.DOCKER_TAG }}

      # 7. Valfritt: Kontrollera om imagen finns i registryt
      - name: Verify Image in Registry
        run: |
          echo "Docker image pushed to registry.cloud.cbh.kth.se/${{ secrets.DOCKER_TAG }}"
